### ISSUE TITLE
Reset Device video not streaming

### ISSUE THREAD

**Issue by osoroshi** [microsoft/vision-ai-developer-kit#261]
Have reset device, removed device in AZ IoTHub, used new host name etc. All modules are running on device and LED solid green but rtsp connections on TCP 9800 are refused. TCP 3000 listening  but no video is displayed 9 previously streaming video fine). In VS Code under the IoT devices ( In Explorer)  the modules display as disconnected.
Cannot find errors in logs on device and Modules report running in AZ IoTHub

_iotedge logs WebStreamModule_
fmpeg exited with code 1 and signal null
Connected clients dropped to 0, so stopping video streaming
Running: ffmpeg -loglevel fatal -i rtsp://192.168.43.41:8900/live -vcodec copy -an -sn -dn -reset_timestamps 1 -movflags empty_moov+default_base_moof+frag_keyframe -bufsize 256k -f mp4 -seekable 0 -headers Access-Control-Allow-Origin:* -content_type video/mp4 http://127.0.0.1:3001/camera
New client connected: ::ffff:192.168.43.49, Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 (1 clients)
ffmpeg exited with code 1 and signal null
New client connected: ::ffff:192.168.43.49, Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763 (2 clients)
A client disconnected; (1 clients remaining)
Connected clients dropped to 0, so stopping video streaming

----------------------------------------------------------------------

 # iotedge logs AIVisionDevKitGetStartedModule
Create model_util
Create properties
Init Properties
Init CameraProperties
Init ModelProperties
Model already present and force update set to false

Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609]

Found IP: 192.168.43.41
ip address = 192.168.43.41
Create camera with no ipc_provider
2019-10-22 11:27:52,287 - iotccsdk - INFO - ipcprovider - connect:263 - API: http://192.168.43.41:1080/login data: {'userpwd': 'admin', 'username': 'admin'}

**Comment by PuneetRahejaMS** [comment]
@osoroshi We are looking into this. Will get back soon.

**Comment by osoroshi** [comment]
Thanks - on start up AIVisionDevKitGetStartedModule does throw an error but does restart but still no video streaming on browser or rtsp


NAME                            STATUS           DESCRIPTION      CONFIG
WebStreamModule                 running          Up 4 minutes     mcr.microsoft.com/aivision/visionsamplemodule:webstream_0.0.13-arm32v7
AIVisionDevKitGetStartedModule  running          Up 4 minutes     mcr.microsoft.com/aivision/visionsamplemodule:1.1.3-arm32v7
edgeHub                         running          Up 4 minutes     mcr.microsoft.com/azureiotedge-hub:1.0
edgeAgent                       running          Up 4 minutes     mcr.microsoft.com/azureiotedge-agent:1.0.7.1





/ # iotedge logs AIVisionDevKitGetStartedModule
Create model_util
Create properties
Init Properties
Init CameraProperties
Init ModelProperties
Model already present and force update set to false

Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609]

Found IP: 192.168.43.41
ip address = 192.168.43.41
Create camera with no ipc_provider
2019-10-22 11:27:52,287 - iotccsdk - INFO - ipcprovider - connect:263 - API: http://192.168.43.41:1080/login data: {'userpwd': 'admin', 'username': 'admin'}
Create model_util
Create properties
Init Properties
Init CameraProperties
Init ModelProperties
Model already present and force update set to false

Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609]

Found IP: 192.168.43.41
ip address = 192.168.43.41
Create camera with no ipc_provider
2019-10-23 04:40:05,107 - iotccsdk - INFO - ipcprovider - connect:263 - API: http://192.168.43.41:1080/login data: {'userpwd': 'admin', 'username': 'admin'}
2019-10-23 04:40:09,689 - iotccsdk - ERROR - ipcprovider - connect:285 - None
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/iotccsdk/ipcprovider.py", line 264, in connect
    response = mysession.post(url, json.dumps(payload))
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main.py", line 141, in <module>
    main(IOT_HUB_PROTOCOL)
  File "./main.py", line 95, in main
    with create_camera() as camera_client:
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/iotccsdk/camera.py", line 112, in connect
    ipc_provider.connect()
  File "/usr/local/lib/python3.5/dist-packages/iotccsdk/ipcprovider.py", line 264, in connect
    response = mysession.post(url, json.dumps(payload))
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
Create model_util
Create properties
Init Properties
Init CameraProperties
Init ModelProperties
Model already present and force update set to false

Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609]

Found IP: 192.168.43.41
ip address = 192.168.43.41
Create camera with no ipc_provider
2019-10-23 04:40:25,741 - iotccsdk - INFO - ipcprovider - connect:263 - API: http://192.168.43.41:1080/login data: {'username': 'admin', 'userpwd': 'admin'}
/ #

**Comment by PuneetRahejaMS** [comment]
@osoroshi Thanks for the additional details. I have a couple of questions. Are both the RTSP and webstreams not working?

So in vlc you tried cameraipaddress:8900
In a web browser you tried cameraipaddress:3000

**Comment by osoroshi** [comment]
@PuneetRahejaMS thanks for reply, 

yes vlc on 8900 and telnet directly port is closed
with browser connect on 3000 but only get black screen no image

Was working fine after reset only recently this seems to be an issue - have changed everything except the Azure Subscription

**Comment by osoroshi** [comment]
Applying latest firmware resolved the issue !
