### ISSUE TITLE
Could not create module AIVisionDevKitGetStartedModule unauthorized: authentication required, StatusCode:500

### ISSUE THREAD

**Issue by V4A001** [microsoft/vision-ai-developer-kit#268]
I am trying to deploy the vision-ai-developer-kit to the device (and I want to run simulator to and debug it :-)). I guess I am missing some credentials to pull it from my container registry? Only question how. Is there some documentation on how to create/ debug own software to this device?

<6> 2019-11-17 13:16:09.755 +00:00 [INF] - Executing command: "Command Group: (\n  [Create module AIVisionDevKitGetStartedModule]\n  [Start module AIVisionDevKitGetStartedModule]\n)"
<6> 2019-11-17 13:16:09.755 +00:00 [INF] - Executing command: "Create module AIVisionDevKitGetStartedModule"
<3> 2019-11-17 13:16:25.320 +00:00 [ERR] - Executing command for operation ["create"] failed.
Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling Create module AIVisionDevKitGetStartedModule: Could not create module AIVisionDevKitGetStartedModule
        caused by: Could not pull image <mycontainerregistry>.azurecr.io/aivisiondevkitgetstartedmodule:0.0.2-arm32v7
        caused by: Get https://<mycontainerregistry>.azurecr.io/v2/aivisiondevkitgetstartedmodule/manifests/0.0.2-arm32v7: unauthorized: authentication required, StatusCode:500, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_01_30.ModuleManagementHttpClient.HandleException(Exception exception, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_01_30/ModuleManagementHttpClient.cs:line 194
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs:line 123
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_01_30.ModuleManagementHttpClient.CreateModuleAsync(ModuleSpec moduleSpec) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_01_30/ModuleManagementHttpClient.cs:line 96
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 59

**Comment by V4A001** [comment]
I added my Azure Container Registry to the Set Modules so that the EdgeAgent was able to pick them up. If you forget the dns 1.1.1.1 or 8.8.8.8 in the setup you are also lost. I believed the docker was smart enough to get them from the deployment, but the connection between the deployment.json and ACR was missing.

I have added those in the set modules instead in my code.

            "registryCredentials": {
              "containerRegistry": {
                "username": "$CONTAINER_REGISTRY_USERNAME",
                "password": "$CONTAINER_REGISTRY_PASSWORD",
                "address": "$CONTAINER_REGISTRY_NAME"
