### ISSUE TITLE
Microsoft.Azure.Devices.Edge.Agent.Core.ConfigSources.ConfigEmptyException: This device has an empty configuration for the edge agent. Please set a deployment manifest.

### ISSUE THREAD

**Issue by MikeWilcoxMicrosoft** [microsoft/vision-ai-developer-kit#286]
We are setting up a new camera.
The camera connected to iothub and then disconnected.  
Now we are getting three green LEDs ie connected to WIFI but NOT connected to IOT hub.

The following is in log file: 

root@miwilcoxbook2:/usr/local/bin/platform-tools# ./adb shell docker logs -f edgeAgent
2019-12-28 00:16:15 +00:00 Starting Edge Agent
2019-12-28 00:16:15.563 +00:00 Edge Agent Main()
<6> 2019-12-28 00:16:16.153 +00:00 [INF] - Initializing Edge Agent.
<6> 2019-12-28 00:16:16.660 +00:00 [INF] - Version - 1.0.8.4.26769994 (7f452949464b45ed67f1cdcc5755654d211674ab)
<6> 2019-12-28 00:16:16.661 +00:00 [INF] -
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2019-12-28 00:16:16.842 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false,"EnableUploadLogs":false}
<6> 2019-12-28 00:16:17.942 +00:00 [INF] - Started operation refresh twin config
<6> 2019-12-28 00:16:18.032 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...
<6> 2019-12-28 00:16:19.215 +00:00 [INF] - Created persistent store at /tmp/edgeAgent
<6> 2019-12-28 00:16:20.641 +00:00 [INF] - Edge agent connected to IoT Hub via Amqp_Tcp_Only.
<6> 2019-12-28 00:16:21.037 +00:00 [INF] - Initialized new module client with subscriptions enabled
<6> 2019-12-28 00:16:21.264 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 1 and reported properties version 1.
<6> 2019-12-28 00:16:21.280 +00:00 [INF] - Deployment config in edge agent's desired properties is empty.
<3> 2019-12-28 00:16:21.293 +00:00 [ERR] - Error refreshing edge agent configuration from twin.
**Microsoft.Azure.Devices.Edge.Agent.Core.ConfigSources.ConfigEmptyException: This device has an empty configuration for the edge agent. Please set a deployment manifest.**
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.UpdateDeploymentConfig(TwinCollection desiredProperties) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 245
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.<RefreshTwinAsync>b__29_0(Twin twin) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 176
<6> 2019-12-28 00:16:21.872 +00:00 [INF] - Updated reported properties
<6> 2019-12-28 00:48:01.318 +00:00 [INF] - Plan execution started for deployment 2
<6> 2019-12-28 00:48:01.363 +00:00 [INF] - Executing command: "Command Group: (\n  [Create module AIVisionDevKitGetStartedModule]\n  [Start module AIVisionDevKitGetStartedModule]\n)"
<6> 2019-12-28 00:48:01.382 +00:00 [INF] - Executing command: "Create module AIVisionDevKitGetStartedModule"
<3> 2019-12-28 00:51:32.295 +00:00 [ERR] - Executing command for operation ["create"] failed.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpBufferedStream.ReadLineAsync(CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpBufferedStream.cs:line 62
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpRequestResponseSerializer.SetResponseStatusLine(HttpResponseMessage httpResponse, HttpBufferedStream bufferedStream, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpRequestResponseSerializer.cs:line 131
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpRequestResponseSerializer.DeserializeResponse(HttpBufferedStream bufferedStream, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpRequestResponseSerializer.cs:line 65
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpUdsMessageHandler.cs:line 36
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2018_06_28.GeneratedCode.EdgeletHttpClient.CreateModuleAsync(String api_version, ModuleSpec module, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2018_06_28/generatedCode/EdgeletHttpClient.cs:line 270
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter[T](Task`1 task, TimeSpan timeout)
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation)

**Comment by PuneetRahejaMS** [comment]
@MikeWilcoxMicrosoft This happens when you create an Edge device in Azure IoT Hub and then launch the Edge runtime before setting up modules for the device in IoT Hub. Once a deployment has been done and the Edge runtime sees it, this should go away.

**Comment by MikeWilcoxMicrosoft** [comment]
re: Edge runtime before setting up modules for the device in IoT Hub. 
Can I get some direction on how to setup the modules in IOT Hub ?

**Comment by PuneetRahejaMS** [comment]
@MikeWilcoxMicrosoft you can refer to https://azure.github.io/Vision-AI-DevKit-Pages/docs/setup/

**Comment by MikeWilcoxMicrosoft** [comment]
No worries... I agree.  
On azure I added the  ‘ AI Vision Dev Kit Get started ‘ to the IOT Edge device I created ( ie the camera) 
via 
Hit select > create > create  and validate > 
After the module was added I had 3 of the 4 modules ie WebStreamModule was not loaded.

**Comment by MikeWilcoxMicrosoft** [comment]
![image](https://user-images.githubusercontent.com/57420850/71737179-9610d600-2e18-11ea-9a47-40a38a67d73a.png)

**Comment by MikeWilcoxMicrosoft** [comment]
![image](https://user-images.githubusercontent.com/57420850/71737302-e5570680-2e18-11ea-9596-e2d8c4ba28a7.png)

**Comment by MikeWilcoxMicrosoft** [comment]
Which Container Registry is the webstream module stored in ?
